{
    "name": "Contact Center UI",
    "summary": "Standalone operational interface for Contact Center agents",
    "version": "16.0.1.1.0",
    "category": "Productivity/Discuss",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/contact-center",
    "license": "AGPL-3",
    "depends": ["contact_center_base", "web"],
    "data": ["views/contact_center_ui_views.xml"],
    "assets": {
        "web.assets_backend": [
            "contact_center_ui/static/src/js/contact_center_model.esm.js",
            "contact_center_ui/static/src/js/structured_content.esm.js",
            "contact_center_ui/static/src/js/browser_attention.esm.js",
            "contact_center_ui/static/src/js/contact_center_store.esm.js",
            "contact_center_ui/static/src/js/deferred_image.esm.js",
            "contact_center_ui/static/src/js/attribution_touchpoints.esm.js",
            "contact_center_ui/static/src/js/connection_health.esm.js",
            "contact_center_ui/static/src/js/conversation_list.esm.js",
            "contact_center_ui/static/src/js/message_content.esm.js",
            "contact_center_ui/static/src/js/conversation_timeline.esm.js",
            "contact_center_ui/static/src/js/voice_recorder.esm.js",
            "contact_center_ui/static/src/js/message_composer.esm.js",
            "contact_center_ui/static/src/js/contact_panel.esm.js",
            "contact_center_ui/static/src/js/contact_center_app.esm.js",
            "contact_center_ui/static/src/js/activity_group_view.esm.js",
            "contact_center_ui/static/src/xml/*.xml",
            "contact_center_ui/static/src/scss/contact_center_app.scss",
        ],
        "web.qunit_suite_tests": [
            "contact_center_ui/static/tests/contact_center_model_tests.esm.js",
        ],
    },
    "application": False,
    "installable": True,
}
