{
    "name": "Contact Center Kanban",
    "summary": "Optional Atendimentos, pipelines and CRM stage synchronization",
    "version": "16.0.1.0.0",
    "category": "Productivity/Discuss",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/contact-center",
    "license": "AGPL-3",
    "depends": ["contact_center_crm"],
    "data": [
        "security/contact_center_kanban_security.xml",
        "security/ir.model.access.csv",
        "security/contact_center_crm_security.xml",
        "views/pipeline_views.xml",
        "views/productivity_views.xml",
        "views/contact_center_crm_views.xml",
        "views/crm_lead_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
