{
    "name": "Contact Center Base",
    "summary": "Provider-neutral contact center foundation",
    "version": "16.0.1.2.1",
    "category": "Productivity/Discuss",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/contact-center",
    "license": "AGPL-3",
    "depends": ["mail", "queue_job", "rating", "web"],
    "data": [
        "security/contact_center_security.xml",
        "security/ir.model.access.csv",
        "security/contact_center_productivity_security.xml",
        "security/resolution_security.xml",
        "data/resolution_reason_data.xml",
        "data/queue_job.xml",
        "data/queue_recovery_cron.xml",
        "data/connection_health_cron.xml",
        "data/onboarding_cron.xml",
        "data/media_cron.xml",
        "views/account_views.xml",
        "views/onboarding_views.xml",
        "views/identity_views.xml",
        "views/channel_views.xml",
        "views/queue_views.xml",
        "views/media_views.xml",
        "views/attribution_views.xml",
        "views/menus.xml",
        "views/resolution_views.xml",
        "views/followup_views.xml",
        "security/conversation_ignore_security.xml",
        "views/conversation_ignore_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "contact_center_base/static/src/js/json_viewer_utils.esm.js",
            "contact_center_base/static/src/js/json_viewer_field.esm.js",
            "contact_center_base/static/src/xml/json_viewer_field.xml",
            "contact_center_base/static/src/scss/json_viewer_field.scss",
            "contact_center_base/static/src/scss/onboarding.scss",
        ],
        "web.qunit_suite_tests": [
            "contact_center_base/static/tests/json_viewer_tests.esm.js",
        ],
    },
    "installable": True,
    "application": False,
}
